export const CLOUDFLARE_LANGUAGES = [
  { code: 'en', name: 'English', weight: 10 },
  { code: 'zh-CN', name: 'Chinese (Simplified)', weight: 7 },
  { code: 'ko', name: 'Korean', weight: 8 },
  { code: 'ru', name: 'Russian', weight: 7 },
  { code: 'zh', name: 'Chinese (generic)', weight: 6 },
  { code: 'zh-TW', name: 'Chinese (Traditional)', weight: 6 },
  { code: 'ja', name: 'Japanese', weight: 6 },
  { code: 'es', name: 'Spanish', weight: 0 },
  { code: 'fr', name: 'French', weight: 0 },
  { code: 'de', name: 'German', weight: 0 },
  { code: 'it', name: 'Italian', weight: 0 },
  { code: 'pt', name: 'Portuguese', weight: 0 },
  { code: 'pt-BR', name: 'Portuguese (Brazil)', weight: 0 },
  { code: 'nl', name: 'Dutch', weight: 0 },
  { code: 'sv', name: 'Swedish', weight: 0 },
  { code: 'no', name: 'Norwegian', weight: 0 },
  { code: 'da', name: 'Danish', weight: 0 },
  { code: 'fi', name: 'Finnish', weight: 0 },
  { code: 'pl', name: 'Polish', weight: 0 },
  { code: 'cs', name: 'Czech', weight: 0 },
  { code: 'hu', name: 'Hungarian', weight: 0 },
  { code: 'ro', name: 'Romanian', weight: 0 },
  { code: 'bg', name: 'Bulgarian', weight: 0 },
  { code: 'el', name: 'Greek', weight: 0 },
  { code: 'tr', name: 'Turkish', weight: 0 },
  { code: 'uk', name: 'Ukrainian', weight: 0 },
  { code: 'he', name: 'Hebrew', weight: 0 },
  { code: 'ar', name: 'Arabic', weight: 0 },
  { code: 'fa', name: 'Persian (Farsi)', weight: 0 },
  { code: 'hi', name: 'Hindi', weight: 0 },
  { code: 'bn', name: 'Bengali', weight: 0 },
  { code: 'pa', name: 'Punjabi', weight: 0 },
  { code: 'gu', name: 'Gujarati', weight: 0 },
  { code: 'ur', name: 'Urdu', weight: 0 },
  { code: 'vi', name: 'Vietnamese', weight: 0 },
  { code: 'id', name: 'Indonesian', weight: 0 },
  { code: 'ms', name: 'Malay', weight: 0 },
  { code: 'th', name: 'Thai', weight: 0 },
] as const;
